name: 功能申请
description: 提交新功能建议
labels: ["enhancement"]
assignees: du2333
body:
  - type: textarea
    attributes:
      label: 描述你想添加的功能
    validations:
      required: true
  - type: textarea
    attributes:
      label: 描述你正在使用的替代方案
